FROM python:3.11-alpine
LABEL maintainer="avburmistrov@mail.ru"

EXPOSE 8000

COPY ./deploy/python/main_app/requirements.txt /
RUN pip install -r requirements.txt --no-cache-dir

COPY ./src/main_app /app
WORKDIR /app

CMD ["uvicorn"  , "--host", "0.0.0.0", "--port", "8000", "main:app"]
