FROM python:3.7-slim

EXPOSE 8080

COPY ./deploy/python/auth_service/requirements.txt /
RUN pip install -r requirements.txt --no-cache-dir

COPY ./src/auth_service /app
WORKDIR /app

CMD ["python", "app.py"]
