apiVersion: v1
kind: Service
metadata:
  name: hw3-service
  labels:
    app: hw3-app
spec:
  type: ClusterIP
  selector:
    app: hw3-app
  ports:
    - name: 80tcp
      port: 80
      protocol: TCP
      targetPort: 8000
