apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: default
  name: nginx-monitor
  labels:
    app: nginx-monitor
spec:
  endpoints:
    - port: prometheus
      scrapeTimeout: 30s
      path: /metrics
      honorLabels: true
      scheme: http
#  jobLabel: stack
  namespaceSelector:
    matchNames:
      - ingress-nginx
  selector:
    matchLabels: []
  
