{
 "title": "HW4-app",
 "time": { "from": "2023-06-29T05:50:43.885Z", "to": "2023-06-29T06:04:47.333Z" },
 "panels": [
  {
   "title": "Latency 0.5q",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, handler) (rate(http_request_duration_seconds_bucket{handler=~\"/api/.*/\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])))",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Latency 0.95q",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, handler) (rate(http_request_duration_seconds_bucket{handler=~\"/api/.*/\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])))",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Latency 0.99q",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, handler) (rate(http_request_duration_seconds_bucket{handler=~\"/api/.*/\"}[2m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])))",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total{handler=~\"/api/.*/\"}[2m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (handler) (rate(nginx_ingress_controller_requests{ingress=\"main-app-ingress\"}[2m]))",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total{handler=~\"/api/.*/\", status=\"5xx\"}[2m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (rate(nginx_ingress_controller_requests{ingress=\"main-app-ingress\", status=\"500\"}[2m]))",
     "legendFormat": "nginx"
    }
   ]
  }
 ]
}